#!/usr/bin/env python3
"""
Download and verify PhysioNet EEGMMIDB and MOABB datasets.

Usage:
  python scripts/download_data.py [--dataset physionet|moabb|both] [--n-subjects N]

This script must succeed before any training runs.
It generates results/dataset_report.md on success.
"""

import argparse
import sys
import os
import logging
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.utils.logging_utils import setup_logging
setup_logging()
logger = logging.getLogger(__name__)


def download_physionet(n_subjects: int = 5, data_dir: str = "data/physionet") -> dict:
    """Download PhysioNet data for first n_subjects as verification."""
    try:
        import mne
        from mne.datasets import eegbci
    except ImportError:
        logger.error("MNE not installed. Run: pip install mne")
        sys.exit(1)

    os.makedirs(data_dir, exist_ok=True)
    logger.info(f"Downloading PhysioNet data for {n_subjects} subjects to {data_dir}")

    subject_stats = []
    failed = []

    for subj in range(1, n_subjects + 1):
        try:
            fnames = eegbci.load_data(subj, runs=[4, 6], path=data_dir, verbose=False)
            raw = mne.io.read_raw_edf(fnames[0], preload=True, verbose=False)
            mne.datasets.eegbci.standardize(raw)

            n_channels = len(raw.ch_names)
            sfreq = raw.info["sfreq"]
            duration = raw.times[-1]

            subject_stats.append({
                "subject": subj,
                "n_channels": n_channels,
                "sfreq": sfreq,
                "duration_sec": round(duration, 1),
                "status": "ok",
            })
            logger.info(f"  Subject {subj}: {n_channels}ch, {sfreq}Hz, {duration:.1f}s OK")

        except Exception as e:
            logger.error(f"  Subject {subj} FAILED: {e}")
            failed.append((subj, str(e)))
            subject_stats.append({"subject": subj, "status": f"FAILED: {e}"})

    return {
        "name": "PhysioNet EEGMMIDB",
        "subjects_checked": n_subjects,
        "failed": failed,
        "stats": subject_stats,
    }


def download_moabb(data_dir: str = "data/moabb") -> dict:
    """Download MOABB BNCI2014_001 dataset."""
    try:
        import moabb
        from moabb.datasets import BNCI2014_001
        from moabb.paradigms import MotorImagery
    except ImportError:
        logger.error("MOABB not installed. Run: pip install moabb")
        return {"name": "BNCI2014_001", "status": "MOABB not installed", "failed": []}

    moabb.set_download_dir(data_dir)
    logger.info(f"Downloading MOABB BNCI2014_001 to {data_dir}")

    try:
        dataset = BNCI2014_001()
        paradigm = MotorImagery(n_classes=4, fmin=1.0, fmax=40.0, tmin=0.0, tmax=4.0)
        # Test with first 2 subjects
        X, y, meta = paradigm.get_data(dataset=dataset, subjects=[1, 2], return_epochs=False)

        return {
            "name": "BNCI2014_001",
            "n_trials_checked": X.shape[0],
            "n_channels": X.shape[1],
            "n_timepoints": X.shape[2],
            "classes": sorted(set(y)),
            "failed": [],
            "status": "ok",
        }
    except Exception as e:
        logger.error(f"MOABB download failed: {e}")
        return {"name": "BNCI2014_001", "status": f"FAILED: {e}", "failed": [(0, str(e))]}


def write_dataset_report(reports: list[dict], save_path: str = "results/dataset_report.md") -> None:
    """Generate dataset report markdown."""
    Path(save_path).parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Dataset Validation Report",
        "",
        "Generated by `scripts/download_data.py`",
        "",
    ]

    for report in reports:
        name = report.get("name", "Unknown")
        lines += [f"## {name}", ""]

        if "stats" in report:
            lines += [
                f"- Subjects checked: {report.get('subjects_checked', 'N/A')}",
                f"- Failed: {len(report.get('failed', []))}",
                "",
                "| Subject | Channels | Freq (Hz) | Duration (s) | Status |",
                "|---------|----------|-----------|--------------|--------|",
            ]
            for s in report["stats"]:
                if s.get("status") == "ok":
                    lines.append(
                        f"| {s['subject']} | {s['n_channels']} | {s['sfreq']} "
                        f"| {s['duration_sec']} | ✓ |"
                    )
                else:
                    lines.append(f"| {s['subject']} | — | — | — | ✗ {s['status']} |")
        else:
            for k, v in report.items():
                if k != "name":
                    lines.append(f"- **{k}**: {v}")

        lines += ["", "---", ""]

    lines += [
        "## Notes",
        "",
        "- PhysioNet data downloaded via MNE `eegbci.load_data()` (EDF format)",
        "- MOABB data downloaded via MOABB benchmark toolbox",
        "- All preprocessing applied post-download (not included in raw data statistics above)",
        "- Channel count may vary; CAR + standard montage alignment applied during preprocessing",
    ]

    Path(save_path).write_text("\n".join(lines))
    logger.info(f"Dataset report written to {save_path}")


def main():
    parser = argparse.ArgumentParser(description="Download and verify EEG datasets")
    parser.add_argument("--dataset", choices=["physionet", "moabb", "both"], default="both")
    parser.add_argument("--n-subjects", type=int, default=5, help="Subjects to verify (default: 5)")
    parser.add_argument("--data-dir-physionet", default="data/physionet")
    parser.add_argument("--data-dir-moabb", default="data/moabb")
    args = parser.parse_args()

    reports = []

    if args.dataset in ("physionet", "both"):
        logger.info("=== PhysioNet EEGMMIDB ===")
        r = download_physionet(args.n_subjects, args.data_dir_physionet)
        reports.append(r)
        if r["failed"]:
            logger.warning(f"{len(r['failed'])} subjects failed to download")

    if args.dataset in ("moabb", "both"):
        logger.info("=== MOABB BNCI2014_001 ===")
        r = download_moabb(args.data_dir_moabb)
        reports.append(r)

    write_dataset_report(reports)

    # Check for critical failures
    all_failed = []
    for r in reports:
        all_failed.extend(r.get("failed", []))

    if all_failed:
        logger.warning(
            f"\n{'='*50}\n"
            f"WARNING: {len(all_failed)} download failure(s).\n"
            f"See results/dataset_report.md for details.\n"
            f"{'='*50}"
        )
        # Don't exit — partial downloads are ok for testing
    else:
        logger.info("\nAll dataset checks passed. Ready for preprocessing and training.")


if __name__ == "__main__":
    main()
